<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cancion
[
<!ELEMENT cancion (titulo, compositor, productor,discogr치fica,artista)>
		<!ELEMENT titulo (#PCDATA)>
		<!ELEMENT compositor (#PCDATA)>
		<!ELEMENT productor (#PCDATA)>
		<!ELEMENT discogr치fica (#PCDATA)>
		<!ELEMENT artista (#PCDATA)>

]>
<cancion>
	<titulo>Rock with you</titulo>
	<compositor>Rod Temperton</compositor>
	<productor>Quincy Jones</productor>
	<discogr치fica>Epic</discogr치fica>
	<artista>Michael Jackson</artista>
</cancion>


