<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cancion
[
<!ELEMENT cancion (titulo,compositores,discográfica,productores,artistas,artista)>
<!ATTLIST cancion duracion CDATA #REQUIRED>
<!ATTLIST cancion año CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT compositores (compositor)>
<!ELEMENT compositor (nombre,apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT productores (productor)>
<!ELEMENT productor (nombre,apellidos)>
<!ELEMENT discográfica (#PCDATA)>
<!ELEMENT artistas (artista)>
<!ELEMENT artista (#PCDATA)>

]>
<cancion duracion="3:40" año="1979">
	<titulo>Rock with you</titulo>
	<compositores>
		<compositor>
			<nombre>Rod</nombre>
			<apellidos>Temperton</apellidos>
		</compositor>
	</compositores>
	<discográfica>Epic</discográfica>
	<productores>
		<productor>
			<nombre>Quincy</nombre>
			<apellidos>Jones</apellidos>
		</productor>
	</productores>
	<artistas>
		<artista>Michael Jackson</artista>
	</artistas>
</cancion>