<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SAFA
[
		<!ELEMENT SAFA (ebooks+)>
		<!ELEMENT ebooks (titulo,autores,modulo,licencia,fechapubli,ISBN,lecciones)>
		<!ELEMENT titulo (#PCDATA)>
		<!ELEMENT autores (autor+)>
		<!ELEMENT autor (#PCDATA)>
		<!ELEMENT modulo (#PCDATA)>
		<!ELEMENT licencia (#PCDATA)>
		<!ELEMENT fechapubli (#PCDATA)>
		<!ELEMENT ISBN (#PCDATA)>
		<!ELEMENT lecciones (leccion+)>
		<!ELEMENT leccion (parrafos,imagenes,animaciones,autoevaluaciones,ejercicios)>
		<!ELEMENT parrafos (#PCDATA)>
		<!ELEMENT imagenes (#PCDATA)>
		<!ELEMENT animaciones (#PCDATA)>
		<!ELEMENT ejercicios (#PCDATA)>
		<!ELEMENT autoevaluaciones (#PCDATA)>



]>
<SAFA>
	<ebooks>
		<titulo>Lenguaje de Marcas</titulo>
		<autores>
			<autor>Alex Tolon</autor>
		</autores>
		<modulo>LMSGI</modulo>
		<licencia>CC3.0</licencia>
		<fechapubli>15 de Septiembre de 2011</fechapubli>
		<ISBN>978929212456</ISBN>
		<lecciones>
			<leccion>
				<parrafos>2</parrafos>
				<imagenes>1</imagenes>
				<animaciones>0</animaciones>
				<autoevaluaciones>2</autoevaluaciones>
				<ejercicios>1</ejercicios>
			</leccion>
			<leccion>
				<parrafos>3</parrafos>
				<imagenes>0</imagenes>
				<animaciones>1</animaciones>
				<autoevaluaciones>1</autoevaluaciones>
				<ejercicios>1</ejercicios>
			</leccion>
		</lecciones>
	</ebooks>
	<ebooks>
		<titulo>Empresa Iniciativa Emprendedora</titulo>
		<autores>
			<autor>Miguel Ángel Sánchez</autor>
			<autor>Xabier Epelde</autor>
		</autores>
		<modulo>EIE</modulo>
		<licencia>Public Domain</licencia>
		<fechapubli>25 de Junio de 2010</fechapubli>
		<ISBN>978439288416</ISBN>
		<lecciones>
			<leccion>
				<parrafos>3</parrafos>
				<imagenes>0</imagenes>
				<animaciones>2</animaciones>
				<autoevaluaciones>1</autoevaluaciones>
				<ejercicios>2</ejercicios>
			</leccion>		
		</lecciones>
	</ebooks>
</SAFA>